---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/5/17 0017 15:09
---
UIType = {
    --[[
    全屏面板
    打开：自动关闭桟中的所有全屏窗口，并将当前窗口提到桟顶
    关闭：自动打开上一个全屏窗口
    --]]
    FullType = 1,
    --[[
    弹出框类型面板
    打开：打开当前面板
    关闭：关闭当前面板
    --]]
    Popup = 2,
}


UIConfig =
{
    [1] = {id = 1,name = "LoginView", type = UIType.FullType, openEvent = UIEvents.LoginView,closeEvent = UIEvents.LoginViewClose ,ctrl = "UI/Modules/LoginView/LoginController", view = "UI/Modules/LoginView/LoginView"},
    [2] = {id = 2,name = "MainView", type = UIType.FullType, openEvent = UIEvents.MainView,closeEvent = UIEvents.MainViewClose ,ctrl = "UI/Modules/MainView/MainController", view = "UI/Modules/MainView/MainView"},
    [3] = {id = 3,name = "BagView", type = UIType.Popup, openEvent = UIEvents.BagView,closeEvent = UIEvents.BagViewClose ,ctrl = "UI/Modules/BagView/BagController", view = "UI/Modules/BagView/BagView"},
}


UIWeidgetCofig =
{
    ["BagInfoView"] = {id=1,name = "BagInfoView",view = "UI/Modules/BagView/BagInfoView"},
}