---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/5/17 0017 14:36
---

UIEvents = {
    LoginView = "LoginView",
    LoginViewClose = "LoginViewClose",

    MainView = "MainView",
    MainViewClose = "MainViewClose",

    BagView = "BagView",
    BagViewClose = "BagViewClose",
}