---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/5/17 0017 14:08
---

---@class BaseView
BaseView = setclass("BaseView")

UIComponent= {
    Image = "Image",
    RawImage = "RawImage",
    Button = "Button",
    Text = "Text",
    InputField = "InputField",
    Slider = "Slider",
    ScrollRect = "ScrollRect",
    Dropdown = "Dropdown",
    Toggle = "Toggle"
}


function BaseView.methods:init(trans,cfg,parentCfg)
    BaseView.transform = trans;
    BaseView.cfg = cfg;
    if parentCfg ~= nil then
        BaseView.parentCfg = parentCfg;
    end
end

function BaseView:OpenChildView(cfg)
    UIManager:OpenChildView(cfg,self.transform,self.cfg);
end

function BaseView:CloseChildView(cfg)
    UIManager:CloseChildView(cfg,self.parentCfg);
end

-- 查找子Transform
function BaseView:Find(sPath, pFrom)
    if not pFrom then
        return self.transform:Find(sPath);
    else
        return pFrom.transform:Find(sPath);
    end
end

-- 注册button点击事件
function BaseView:AddOnClick(sPath, action, pFrom)
    local btn = self:GetComponent(UIComponent.Button, sPath, pFrom);
    btn.onClick:RemoveAllListeners();
    btn.onClick:AddListener(function() action(self,btn.gameObject); end);
end

function BaseView:AddBtnOnClick(btn, action)
    btn.onClick:RemoveAllListeners();
    btn.onClick:AddListener(function() action(self,btn.gameObject); end);
end


function BaseView:GetComponent(sType, sPath, pFrom)
    local trans = pFrom or self.transform;
    if sPath and #sPath > 0 then
        trans = trans:Find(sPath)
    end;
    if not trans then
        return nil
    end;
    return trans:GetComponent(sType);
end


function BaseView:AddEvent(eventName,handler)
    Game.GlobalEvent:AddEvent(eventName,handler);
end

function BaseView:RemoveEvent(eventName,handler)
    Game.GlobalEvent:RemoveEvent(eventName,handler);
end

return BaseView;