---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/5/20 0020 10:43
---

---@class BagController
local this = setclass("BagController")

function this.methods:init(id)
    this.id = id;
    this.cfg = UIConfig[id];
    Game.GlobalEvent:AddEvent(this.cfg.openEvent,this.OnOpen);
    Game.GlobalEvent:AddEvent(this.cfg.closeEvent,this.OnClose);
    this:OnInit();
end

function this:OnInit()
    log("~~~~~~~~~~ BagController OnInit")
end

function this:OnOpen()
    UIManager:OpenUI(this.id);
end

function this:OnClose()
    UIManager:CloseUI(this.id);
end

return this;
