---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/5/10 0010 14:08
---

Game = setclass("Game");
--游戏开始入口
function Game.Init()
    log("Game Init ~~~~~~~~~~~~~~~")
    Game.GlobalEvent = GameEvent:New();
    require('UI/Core/UIManager'):new();
    Game.InitModules();
    log("Game Init Complete~~~~~~~~~~~~~~~")

    dispatchEvent(UIEvents.LoginView)
end

function Game.InitModules()
    require("UI/Core/BaseView")
    for k, v in pairs(UIConfig) do
        ---@type BaseObject
        local view = reimport(v.ctrl);
        view:new(v.id);
    end
end

return Game;